---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-static-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  storageClassName: fsx
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: ${filesystem_id}
    volumeAttributes:
      dnsname: ${dns_name}
      mountname: ${mount_name}