apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-static-pvc
  namespace: slurm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx
  resources:
    requests:
      storage: 1200Gi
  volumeName: fsx-static-pv